language: bash

install:
    - mkdir bin
    - bashbrewVersion="$(< bashbrew-version)"
    - wget -O bin/bashbrew "https://github.com/docker-library/bashbrew/releases/download/v$bashbrewVersion/bashbrew-amd64"
    - chmod +x bin/bashbrew
    - export PATH="$PWD/bin:$PATH"
    - bashbrew --version

before_script:
    - env | sort

script:
    - ./.travis.sh
